export const FIELDS = {
  input: "text",
  radio: "radio",
  radioQuestion: "radioQuestion",
  inputQuestion: "inputQuestion",
  date: "date",
  image: "file",
  textArea: "textArea",
  checkBoxQuestion: "checkBoxQuestion",
  switch: "switch",
  increament: "increament",
  dropDown: "dropdown",
  password: "password",
  component: "component",
  imageBanner: "imageBanner",
  radioEmoji: "radioEmoji",
  time: "time",
  select: "select",
};
